#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define UNICODE_SELECTED_MODES UC_LNX, UC_OSX
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))

#define ENCODER_RESOLUTION 4

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#define TAPPING_TERM 200
// #define TAPPING_TERM_PR_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
// #define PERMISSIVE_HOLD
// #define RETRO_TAPPING