#pragma once

#define UNICODE_SELECTED_MODES UC_LNX, UC_OSX
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))

#define QMK_KEYS_PER_SCAN 4
#define FORCE_NKRO
#define ENCODER_RESOLUTION 4

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#define COMBO_VARIABLE_LEN
#define COMBO_TERM 20
#define COMBO_MOD_TERM 200
#define COMBO_MUST_HOLD_MODS
#define COMBO_PERMISSIVE_HOLD

 #define TAPPING_TERM 150
//  #define TAPPING_FORCE_HOLD
// #define IGNORE_MOD_TAP_INTERRUPT
// #define PERMISSIVE_HOLD

#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
