#pragma once

#define UNICODE_SELECTED_MODES UC_LNX, UC_OSX
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))

#define ENCODER_RESOLUTION 4

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#define COMBO_COUNT 20
#define COMBO_TERM  30
// #define COMBO_ALLOW_ACTION_KEYS

#define FORCE_NKRO

#define TAPPING_TERM 200
// #define TAPPING_TERM_PR_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define QMK_KEYS_PER_SCAN 4
// #define PERMISSIVE_HOLD
// #define RETRO_TAPPING



// #undef MOUSEKEY_MAX_SPEED
// #define MOUSEKEY_MAX_SPEED 7
// #undef MOUSEKEY_WHEEL_INTERVAL
// #define MOUSEKEY_WHEEL_INTERVAL 50
// #undef MOUSEKEY_WHEEL_DELAY
// #define MOUSEKEY_WHEEL_DELAY 200
