#pragma once

#define UNICODE_SELECTED_MODES UC_LNX, UC_OSX
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))

#define QMK_KEYS_PER_SCAN 4
#define FORCE_NKRO
#define ENCODER_RESOLUTION 4

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#define COMBO_VARIABLE_LEN
#define COMBO_TERM 30
#define COMBO_PERMISSIVE_HOLD

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
