#pragma once

#define S_Q S(KC_Q)
#define S_W S(KC_W)
#define S_E S(KC_E)
#define S_R S(KC_R)
#define S_T S(KC_T)
#define S_Y S(KC_Y)
#define S_U S(KC_U)
#define S_I S(KC_I)
#define S_O S(KC_O)
#define S_P S(KC_P)

#define S_A S(KC_A)
#define S_S S(KC_S)
#define S_D S(KC_D)
#define S_F S(KC_F)
#define S_G S(KC_G)
#define S_H S(KC_H)
#define S_J S(KC_J)
#define S_K S(KC_K)
#define S_L S(KC_L)

#define S_Z S(KC_Z)
#define S_X S(KC_X)
#define S_C S(KC_C)
#define S_V S(KC_V)
#define S_B S(KC_B)
#define S_N S(KC_N)
#define S_M S(KC_M)
